### ISSUE TITLE
chromeapp:samples "Client ID is below specific application key"

### ISSUE THREAD

**Issue by jascination** [yeoman/generator-chromeapp#51]
When trying to use `chromeapp:samples` I'm getting the following error:

````
What sample would you like to use? identity
   create app/assets/screenshot_1280_800.png
   create app/identity.js
   create app/index.html
   create app/main.js
   create app/manifest.json
   create app/README.md
   create app/sample_support_metadata.json
   create app/sample_support/google-code-prettify/lang-css.js
   create app/sample_support/google-code-prettify/run_prettify.js
   create app/sample_support/prettify_theme.css
   create app/sample_support/prettify.css
   create app/sample_support/prettify.js
   create app/sample_support/README.md
   create app/sample_support/sample_support.js
   create app/sample_support/show_snippets.html
   create app/sample_support/show_snippets.js
   create app/sample_support/snippets.css
   create app/sample_support/standard.css
undefined:14
    // client_id below is specifc to the application key. Follow the
    ^
SyntaxError: Unexpected token /
    at Object.parse (native)
    at module.exports.yeoman.generators.Base.extend.manifest (/usr/local/lib/node_modules/generator-chromeapp/samples/index.js:186:21)
    at /usr/local/lib/node_modules/generator-chromeapp/node_modules/yeoman-generator/lib/base.js:395:14
    at processImmediate [as _immediateCallback] (timers.js:358:17)

````

**Comment by ragingwind** [comment]
They use comment in JSON to explain you what to do. see: https://github.com/GoogleChrome/chrome-app-samples/blob/master/samples/identity/manifest.json. at this time, you need to download and use the sample manually without the yeoman generator

**Comment by jascination** [comment]
So does that mean the generator is currently non-functioning and chrome:samples can't be used with yeoman?

**Comment by ragingwind** [comment]
No. Some samples can be has an issue like `identity` Not all

**Comment by ragingwind** [comment]
@jascination I think It works well now. I've patched for this https://github.com/yeoman/generator-chromeapp/commit/7f7c87e1587e3b271b61a8f6b7782ebca248a105
