### ISSUE TITLE
 Cannot find module '../manifest'

### ISSUE THREAD

**Issue by gerswin** [yeoman/generator-chromeapp#55]
/usr/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:580
    throw e;
          ^
Error: Cannot find module '../manifest'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/generator-chromeapp/app/index.js:6:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Ubuntu Gnome 14.10 fresh install
npm -v
1.4.28
node -v
v0.10.37

**Comment by ragingwind** [comment]
Thanks for reporting. fixed by https://github.com/yeoman/generator-chromeapp/commit/6eb8f9f01f290e3ddea33009beeb914e7c7279f1
